{
  "swagger" : "2.0",
  "info" : {
    "description" : "FAA Airport Status Web Service API",
    "version" : "1.1.0",
    "title" : "Airport Status Web Service",
    "contact" : {
      "name" : "Airport Status Web Service (ASWS)",
      "url" : "http://fly.faa.gov",
      "email" : "edai-aero@faa.gov"
    },
    "license" : {
      "name" : "Creative Commons 0 (CC0)",
      "url" : "https://creativecommons.org/publicdomain/zero/1.0/legalcode"
    }
  },
  "host" : "soa.smext.faa.gov",
  "basePath" : "/asws",
  "tags" : [ {
    "name" : "FAA Airport Status Service"
  } ],
  "schemes" : [ "https" ],
  "paths" : {
    "/api/airport/delays" : {
      "get" : {
        "tags" : [ "FAA Airport Status Service" ],
        "summary" : "Get airport delay summary for major US national airports.",
        "description" : "The airport status is retrieved from fly.faa.gov and is provided in a format that can be used by applications that require airport status data.Delays will be returned for the following airports: BOS, LGA, TEB, EWR, JFK, PHL, PIT, IAD, BWI, DCA, RDU, CLT, ATL, MCO, TPA, MCO, FLL, MIA, DTW, CLE, MDW, ORD, IND, CVG, BNA, MEM, STL, MCI, MSP, DFW, IAH, DEN, SLC, PHX, LAS, SAN, LAX, SJC, SFO, PDX, SEA",
        "operationId" : "getDelays",
        "produces" : [ "application/json", "application/xml" ],
        "parameters" : [ ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "schema" : {
              "$ref" : "#/definitions/Delays"
            }
          },
          "404" : {
            "description" : "Airport delays from http://www.fly.faa.gov are unavailable"
          },
          "500" : {
            "description" : "Airport information from http://www.fly.faa.gov returned an error response"
          }
        }
      }
    },
    "/api/airport/status/{airportCode}" : {
      "get" : {
        "tags" : [ "FAA Airport Status Service" ],
        "summary" : "Get airport status based on path parameter provided on the API call. The path parameter is an IATA airport code.",
        "description" : "The airport status is retrieved from fly.faa.gov and is provided in a format that can be used by applications that require airport status data.Available airports include the following: BOS, LGA, TEB, EWR, JFK, PHL, PIT, IAD, BWI, DCA, RDU, CLT, ATL, MCO, TPA, MCO, FLL, MIA, DTW, CLE, MDW, ORD, IND, CVG, BNA, MEM, STL, MCI, MSP, DFW, IAH, DEN, SLC, PHX, LAS, SAN, LAX, SJC, SFO, PDX, SEA",
        "operationId" : "getAirportStatus",
        "produces" : [ "application/json", "application/xml" ],
        "parameters" : [ {
          "name" : "airportCode",
          "in" : "path",
          "required" : true,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "schema" : {
              "$ref" : "#/definitions/AirportStatus"
            }
          },
          "404" : {
            "description" : "Delays are available only for major United States airports"
          }
        }
      }
    }
  },
  "definitions" : {
    "Status" : {
      "type" : "object",
      "required" : [ "avgDelay", "closureBegin", "closureEnd", "endTime", "maxDelay", "minDelay", "reason", "trend", "type" ],
      "properties" : {
        "type" : {
          "type" : "string",
          "xml" : {
            "name" : "Type"
          }
        },
        "reason" : {
          "type" : "string",
          "xml" : {
            "name" : "Reason"
          }
        },
        "avgDelay" : {
          "type" : "string",
          "xml" : {
            "name" : "AvgDelay"
          }
        },
        "closureEnd" : {
          "type" : "string",
          "xml" : {
            "name" : "ClosureEnd"
          }
        },
        "closureBegin" : {
          "type" : "string",
          "xml" : {
            "name" : "ClosureBegin"
          }
        },
        "minDelay" : {
          "type" : "string",
          "xml" : {
            "name" : "MinDelay"
          }
        },
        "trend" : {
          "type" : "string",
          "xml" : {
            "name" : "Trend"
          }
        },
        "maxDelay" : {
          "type" : "string",
          "xml" : {
            "name" : "MaxDelay"
          }
        },
        "endTime" : {
          "type" : "string",
          "xml" : {
            "name" : "EndTime"
          }
        }
      },
      "example" : {
        "minDelay" : "minDelay",
        "maxDelay" : "maxDelay",
        "reason" : "reason",
        "closureEnd" : "closureEnd",
        "closureBegin" : "closureBegin",
        "avgDelay" : "avgDelay",
        "trend" : "trend",
        "endTime" : "endTime",
        "type" : "type"
      },
      "xml" : {
        "name" : "Status"
      }
    },
    "Weather" : {
      "type" : "object",
      "properties" : {
        "content" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "properties" : { }
          }
        }
      },
      "example" : {
        "content" : [ "{}", "{}" ]
      },
      "xml" : {
        "name" : "Weather"
      }
    },
    "GroundDelay" : {
      "type" : "object",
      "required" : [ "airport", "avgTime", "reason" ],
      "properties" : {
        "airport" : {
          "type" : "string",
          "xml" : {
            "name" : "airport"
          }
        },
        "avgTime" : {
          "type" : "string",
          "xml" : {
            "name" : "avgTime"
          }
        },
        "reason" : {
          "type" : "string",
          "xml" : {
            "name" : "reason"
          }
        }
      },
      "example" : {
        "reason" : "reason",
        "avgTime" : "avgTime",
        "airport" : "airport"
      },
      "xml" : {
        "name" : "GroundDelay"
      }
    },
    "GroundStop" : {
      "type" : "object",
      "required" : [ "airport", "endTime", "reason" ],
      "properties" : {
        "airport" : {
          "type" : "string",
          "xml" : {
            "name" : "airport"
          }
        },
        "endTime" : {
          "type" : "string",
          "xml" : {
            "name" : "endTime"
          }
        },
        "reason" : {
          "type" : "string",
          "xml" : {
            "name" : "reason"
          }
        }
      },
      "example" : {
        "reason" : "reason",
        "endTime" : "endTime",
        "airport" : "airport"
      },
      "xml" : {
        "name" : "GroundStop"
      }
    },
    "ArriveDepartDelay" : {
      "type" : "object",
      "required" : [ "airport", "maxTime", "minTime", "reason" ],
      "properties" : {
        "airport" : {
          "type" : "string",
          "xml" : {
            "name" : "airport"
          }
        },
        "maxTime" : {
          "type" : "string",
          "xml" : {
            "name" : "maxTime"
          }
        },
        "reason" : {
          "type" : "string",
          "xml" : {
            "name" : "reason"
          }
        },
        "minTime" : {
          "type" : "string",
          "xml" : {
            "name" : "minTime"
          }
        }
      },
      "example" : {
        "maxTime" : "maxTime",
        "reason" : "reason",
        "minTime" : "minTime",
        "airport" : "airport"
      },
      "xml" : {
        "name" : "ArriveDepartDelay"
      }
    },
    "Closure" : {
      "type" : "object",
      "required" : [ "airport", "reason", "reopen" ],
      "properties" : {
        "airport" : {
          "type" : "string",
          "xml" : {
            "name" : "airport"
          }
        },
        "reason" : {
          "type" : "string",
          "xml" : {
            "name" : "reason"
          }
        },
        "reopen" : {
          "type" : "string",
          "xml" : {
            "name" : "reopen"
          }
        }
      },
      "example" : {
        "reason" : "reason",
        "reopen" : "reopen",
        "airport" : "airport"
      },
      "xml" : {
        "name" : "closure"
      }
    },
    "GroundDelays" : {
      "type" : "object",
      "properties" : {
        "GroundDelay" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/GroundDelay"
          }
        }
      },
      "example" : {
        "GroundDelay" : [ {
          "reason" : "reason",
          "avgTime" : "avgTime",
          "airport" : "airport"
        }, {
          "reason" : "reason",
          "avgTime" : "avgTime",
          "airport" : "airport"
        } ]
      }
    },
    "GroundStops" : {
      "type" : "object",
      "properties" : {
        "GroundStop" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/GroundStop"
          }
        }
      },
      "example" : {
        "GroundStop" : [ {
          "reason" : "reason",
          "endTime" : "endTime",
          "airport" : "airport"
        }, {
          "reason" : "reason",
          "endTime" : "endTime",
          "airport" : "airport"
        } ]
      }
    },
    "ArriveDepartDelays" : {
      "type" : "object",
      "properties" : {
        "ArriveDepartDelay" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/ArriveDepartDelay"
          }
        }
      },
      "example" : {
        "ArriveDepartDelay" : [ {
          "maxTime" : "maxTime",
          "reason" : "reason",
          "minTime" : "minTime",
          "airport" : "airport"
        }, {
          "maxTime" : "maxTime",
          "reason" : "reason",
          "minTime" : "minTime",
          "airport" : "airport"
        } ]
      }
    },
    "Closures" : {
      "type" : "object",
      "properties" : {
        "Closure" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/Closure"
          }
        }
      },
      "example" : {
        "Closure" : [ {
          "reason" : "reason",
          "reopen" : "reopen",
          "airport" : "airport"
        }, {
          "reason" : "reason",
          "reopen" : "reopen",
          "airport" : "airport"
        } ]
      }
    },
    "Delays" : {
      "type" : "object",
      "properties" : {
        "GroundDelays" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/GroundDelays"
          }
        },
        "GroundStops" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/GroundStops"
          }
        },
        "ArriveDepartDelays" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/ArriveDepartDelays"
          }
        },
        "Closures" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/Closures"
          }
        }
      },
      "example" : {
        "GroundDelays" : [ {
          "GroundDelay" : [ {
            "reason" : "reason",
            "avgTime" : "avgTime",
            "airport" : "airport"
          }, {
            "reason" : "reason",
            "avgTime" : "avgTime",
            "airport" : "airport"
          } ]
        }, {
          "GroundDelay" : [ {
            "reason" : "reason",
            "avgTime" : "avgTime",
            "airport" : "airport"
          }, {
            "reason" : "reason",
            "avgTime" : "avgTime",
            "airport" : "airport"
          } ]
        } ],
        "ArriveDepartDelays" : [ {
          "ArriveDepartDelay" : [ {
            "maxTime" : "maxTime",
            "reason" : "reason",
            "minTime" : "minTime",
            "airport" : "airport"
          }, {
            "maxTime" : "maxTime",
            "reason" : "reason",
            "minTime" : "minTime",
            "airport" : "airport"
          } ]
        }, {
          "ArriveDepartDelay" : [ {
            "maxTime" : "maxTime",
            "reason" : "reason",
            "minTime" : "minTime",
            "airport" : "airport"
          }, {
            "maxTime" : "maxTime",
            "reason" : "reason",
            "minTime" : "minTime",
            "airport" : "airport"
          } ]
        } ],
        "GroundStops" : [ {
          "GroundStop" : [ {
            "reason" : "reason",
            "endTime" : "endTime",
            "airport" : "airport"
          }, {
            "reason" : "reason",
            "endTime" : "endTime",
            "airport" : "airport"
          } ]
        }, {
          "GroundStop" : [ {
            "reason" : "reason",
            "endTime" : "endTime",
            "airport" : "airport"
          }, {
            "reason" : "reason",
            "endTime" : "endTime",
            "airport" : "airport"
          } ]
        } ],
        "Closures" : [ {
          "Closure" : [ {
            "reason" : "reason",
            "reopen" : "reopen",
            "airport" : "airport"
          }, {
            "reason" : "reason",
            "reopen" : "reopen",
            "airport" : "airport"
          } ]
        }, {
          "Closure" : [ {
            "reason" : "reason",
            "reopen" : "reopen",
            "airport" : "airport"
          }, {
            "reason" : "reason",
            "reopen" : "reopen",
            "airport" : "airport"
          } ]
        } ]
      },
      "xml" : {
        "name" : "Delays"
      }
    },
    "AirportStatus" : {
      "type" : "object",
      "required" : [ "city", "delay", "delayCount", "iata", "icao", "name", "state", "supportedAirport", "weather" ],
      "properties" : {
        "name" : {
          "type" : "string",
          "xml" : {
            "name" : "Name"
          }
        },
        "city" : {
          "type" : "string",
          "xml" : {
            "name" : "City"
          }
        },
        "state" : {
          "type" : "string",
          "xml" : {
            "name" : "State"
          }
        },
        "icao" : {
          "type" : "string",
          "xml" : {
            "name" : "ICAO"
          }
        },
        "iata" : {
          "type" : "string",
          "xml" : {
            "name" : "IATA"
          }
        },
        "supportedAirport" : {
          "type" : "boolean",
          "xml" : {
            "name" : "SupportedAirport"
          }
        },
        "delay" : {
          "type" : "boolean",
          "xml" : {
            "name" : "Delay"
          },
          "default" : false
        },
        "delayCount" : {
          "type" : "integer",
          "xml" : {
            "name" : "DelayCount"
          }
        },
        "status" : {
          "type" : "array",
          "xml" : {
            "name" : "Status"
          },
          "items" : {
            "$ref" : "#/definitions/Status"
          }
        },
        "weather" : {
          "xml" : {
            "name" : "Weather"
          },
          "$ref" : "#/definitions/Weather"
        }
      },
      "example" : {
        "delay" : false,
        "iata" : "iata",
        "city" : "city",
        "delayCount" : 0,
        "name" : "name",
        "weather" : {
          "content" : [ "{}", "{}" ]
        },
        "icao" : "icao",
        "state" : "state",
        "supportedAirport" : true,
        "status" : [ {
          "minDelay" : "minDelay",
          "maxDelay" : "maxDelay",
          "reason" : "reason",
          "closureEnd" : "closureEnd",
          "closureBegin" : "closureBegin",
          "avgDelay" : "avgDelay",
          "trend" : "trend",
          "endTime" : "endTime",
          "type" : "type"
        }, {
          "minDelay" : "minDelay",
          "maxDelay" : "maxDelay",
          "reason" : "reason",
          "closureEnd" : "closureEnd",
          "closureBegin" : "closureBegin",
          "avgDelay" : "avgDelay",
          "trend" : "trend",
          "endTime" : "endTime",
          "type" : "type"
        } ]
      },
      "xml" : {
        "name" : "AirportStatus"
      }
    }
  }
}